# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e878b06329907a33f18969fdddd99b39face13a737d21f11129ccc1ee22e98485ae2adb2dbc22b1b226e43606ed9adfd8d833f86133116dcd45c3bda64043a3

test:
  secret_key_base: 6f69ed8e1b3e3769e446a6f17b2732a5fddedf7ad1395ed8886088ebf1140f4520d0877270385bbf56e2a7966fd9b648c4c90ec01eea16f0aa4e602b5ca35ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
